name: Get Vault Secrets/ AWS Creds
jobs:
  build-and-push:
    runs-on: k8s-self-hosted
    steps:
# ------------------------------------------------------------
    - name: Checkout Common Actions
      uses: actions/checkout@v2
      with:
        repository: myfitnesspal/github-actions
        ref: main
        ssh-key: ${{ secrets.MFP_GITHUB_ACTIONS_SSH_KEY }}
        path: .github/common-actions
# ------------------------------------------------------------
    - name: Get Secrets and AWS Creds
      id: generic
      uses: ./.github/common-actions/get-vault-secrets
      with:
        secretId: ${{ secrets.vault_secret_id }}
        exportAWS: true   # Required for AWS credentials. NOTE: Make sure you have requested access through mfp-terraform-atlantis
        secrets:
          # TODO Fill this out for secrets stored in Vault at path "ci/<your-repo>/some-login"
          # some-login password | SOME_LOGIN_PASSWORD ;
          # some-login username
